### ISSUE TITLE
error when calling its classFactory() method

### ISSUE THREAD

**Issue by lfurtkevicova** [jeleniste/islh_parser#2]
Po pridaní repozitára do zložky `.qgis2/python/plugins` a po inštalácii modulov `simplejson` a `lxml` sa objaví niečo ako toto:

![error](https://cloud.githubusercontent.com/assets/13394357/12750856/fdbd8338-c9b9-11e5-95a0-2ab4619e6174.png)

_Pozn.:_ používam Ubuntu 14.04 a QGIS 2.12.1-Lyon

**Comment by jeleniste** [comment]
Ou jasne, sem to zaktualizoval a zapomel nahrat jeden modul na git.

**Comment by jeleniste** [comment]
Prosimte, muzes to zkusit znova?

**Comment by lfurtkevicova** [comment]
Ok, už to šlape .. 
plus ešte maličký detail .. v popise pluginu "Umožňuje ... standaRtu lesního hospodářství"  .. inak super !

**Comment by jeleniste** [comment]
Díky.
